<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ5aogr2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ5aogr2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJ5aogr2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJ5aogr2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJ5aogr2\appProdProjectContainer([
    'container.build_hash' => 'J5aogr2',
    'container.build_id' => '28f6bfae',
    'container.build_time' => 1618317697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ5aogr2');
