<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrzlhkz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrzlhkz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCrzlhkz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCrzlhkz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCrzlhkz\appDevDebugProjectContainer([
    'container.build_hash' => 'Crzlhkz',
    'container.build_id' => 'df1f82d1',
    'container.build_time' => 1618434742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrzlhkz');
